/*
 *
 * HomePage constants
 *
 */

export const DEFAULT_ACTION = 'app/HomePage/DEFAULT_ACTION';
export const SAVE_ASSESSMENT = 'app/HomePage/SAVE_ASSESSMENT';
export const SAVE_ASSESSMENT_SUCCESS = 'app/HomePage/SAVE_ASSESSMENT_SUCCESS';
export const SAVE_ASSESSMENT_ERROR = 'app/HomePage/SAVE_ASSESSMENT_ERROR';
export const GET_ASSESSMENT_QUESTIONS = 'app/HomePage/GET_ASSESSMENT_QUESTIONS';
export const GET_ASSESSMENT_QUESTIONS_SUCCESS = 'app/HomePage/GET_ASSESSMENT_QUESTIONS_SUCCESS';
export const GET_ASSESSMENT_QUESTIONS_ERROR = 'app/HomePage/GET_ASSESSMENT_QUESTIONS_ERROR';
